name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  ci:
    uses: lambda-script/shared-workflows/.github/workflows/ci.yml@0105af4e12ad593ecaf9d4bef668315f887581cf # v1
    with:
      package_manager: pnpm
      node_versions: '["20", "22"]'
      test_script: test
