name: Release Please

on:
  push:
    branches: [main]

jobs:
  release:
    uses: lambda-script/shared-workflows/.github/workflows/release-please.yml@0105af4e12ad593ecaf9d4bef668315f887581cf # v1
    secrets:
      token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
